### ISSUE TITLE
Locate on punctuation looks up the empty string

### ISSUE THREAD

**Issue by gsg** [the-lambda-church/merlin#315]
Running locate on various bits of OCaml punctuation results in merlin trying to look up the empty string. In the case that the punctuation is '=', it looks up '=' and usually finds `Pervasives.(=)` and proceeds to complain that the definition isn't available.

It would be better to gently refuse such nonsensical requests with a nice message.

**Comment by trefis** [comment]
Ok so, two things here : 
1. since 920bd6ff729becd80e8d994608a8ed598bdda038 , merlin will not try to locate the empty string (hurrah!)
2. with the way locate (and type-enclosing) are implemented, we do not have sufficient to differentiate between the case where the `=` you're looking up/typing is an operator and the one where it is a keyword (in which case the request doesn't make sense).
But I feel like in these case, it is ok to try and type/locate `=`-the-operator.
