### ISSUE TITLE
Locate of a type variable looks up that name

### ISSUE THREAD

**Issue by gsg** [the-lambda-church/merlin#317]
Locate on `'a` will look up `a`, which isn't very helpful. Probably better to decline with a message.

**Comment by trefis** [comment]
I agree that it would be nicer if this was gracefully handled, however doing so requires modifying a pretty ugly piece of code (namely https://github.com/the-lambda-church/merlin/blob/master/src/kernel/merlin_lexer.ml#L200 ) and I would rather not do so.

I'm closing the issue, if you disagree because you find this bug really annoying don't hesitate to tell us, and I'll reconsider.

**Comment by gasche** [comment]
Out of curiosity I reconstructed the code in a pseudo-code format to understand what it does. `!` denotes the end of the "head" (whatever it is, I have no idea what `History` represents):

```
let h = parse (focus h) with
  | . { h+1}
  | _ { h }
in
parse (h !) with
| x=operator !       { [x] }
| x=operator ¬( _ !       { [x] }
| _ {
  let acc, h = parse (h ! tail h) with
    | x=ident _ !          { [x], h }
    | ( _ ! x=operator ) { [x], h }
    | x=operator ( _ ! ) { [x], h - 1 } 
    | ) x=operator ( _ !   { [x], h - 2 }
    | _ { [], h }
  in
  let h = h - 1 in
  let rec head acc = parse (h !) with
    | . x=ident tl  { head (x :: acc) hl }
    | . x=ident ! { ident :: acc }
    | _             { acc }
  in head acc
}
```

Given the PR context, it looks like this code selects an OCaml identifier the user is "probably enquiring about" when asking for feedback as an arbitrary position in the text buffer. In prose, the implementation seems to do the following:
- if we are just on a dot, skip it and move to the right
- if we are on an operator that is not followed by an opening parenthesis (why single that case out?), this is the identifier to return
- if we are on an identifier or parenthesized operator (that is, `foo` or `( + )`), look for a module path before (that is, `M.N.foo` or `M.N.(+)`) and return the path (that is, `[foo;N;M]` or `[+; N; M]`)
- if we are on an operator *outside* parentheses (that is, `) + (`), (move before the closing parens and) collect the module path as well. Why would you do that?
- otherwise just give up

**Comment by trefis** [comment]
I am not sure, but I believe your interpretation is wrong.
The resulting list of `History.head` is the prefix (i.e. before focused) stream of tokens in *reversed* order -- that's what I understand from the description of `History.t`, i.e. "A sort of zipper".

With this interpretation, the second case would be : "if we are on an operator which is not preceded by an opening parenthesis", and this case is explained by the (new interpretation of the) fourth one : "if we are *inside* parenthesis, move before the closing parens and collect the module path as well".

With this interpretation, that last point makes a lot more sense, doesn't it? If we are on the `+` in `MyModule.Which.Redefines.(+)` we want to be looking for that whole path, not just `+`.

Does this make sense?

I agree with you that this is highly unreadable and hard to understand, some comments might help.
A better syntax for this kind of things (either actual syntax, or just having it written in a better way) would also go a long way too.
(Your pseudo code was nice in that regard, except for the `|` used as terminator, which wasn't really noticeable, and can be confused with a case separator.)

PS: Now that this has been written in clearer term the case where we have an operator just after an opening parenthesis could wrong if we are on a prefix operator).

**Comment by trefis** [comment]
PS2: the commit message on https://github.com/the-lambda-church/merlin/commit/fc0b152509786b16c0ff38976af02ee30bf77b4c is lovely. We should probably have it in a comment in that file.

**Comment by gasche** [comment]
Indeed, with the head reversed this make much more sense. The pseudo-code becomes the following:

```
let h = parse (focus h) with
  | . { h+1 }
  | _ { h }
in
parse h with
| BOF x=operator       { [x] }
| ¬( x=operator        { [x] }
| _ {
  let acc, h = parse (h ! tail h) with
    | x=ident !          { [x], h }
    | ( ! x=operator )   { [x], h }
    | ( x=operator ! )   { [x], h - 1 } 
    | ( x=operator ) !   { [x], h - 2 }
    | _ { [], h }
  in
  let h = h - 1 in
  let rec head acc = parse (h !) with
    | tl x=ident .  { head (x :: acc) hl }
    | x=ident . !   { ident :: acc }
    | _             { acc }
  in head acc
}
```
(And the module path components are now returned in the natural order.)

**Comment by gasche** [comment]
With this pseudo-code I can suggest adding the following case:

```
parse h with
| BOF x=operator       { [x] }
| ¬( x=operator        { [x] }
| ' x=ident            { [] }
| _ { ... }
```

That is, something like the following:

```
| List.More ((_, id), (List.More ((_, rest), _) | List.One (_, rest)))
  when Raw_parser_values.is_ident id && Raw_parser_values.is_quote rest -> []
```

**Comment by trefis** [comment]
It is actually obvious with that notation yes.
I will do so and add the pseudo-code description in a comment (until we manage to make the code itself cleaner).

Thank you!

**Comment by gasche** [comment]
To make the code readable you would need a combinator library that would allow to define (first-class) patterns of dynamically known (fixed) size, check them "around" the current focus and return the focus shifted to the beginning of the pattern. In particular, a single call would factorize the three following lines:

```
    | ( ! x=operator )   { [x], h }
    | ( x=operator ! )   { [x], h - 1 } 
    | ( x=operator ) !   { [x], h - 2 }
```

with something like
```
let pat = Lexpat.(token lparen ** of_option match_operator ** token rparen) in
match Lexpat.match_and_shift pat h with
| Some (op, h) -> ...
| None -> ...
```

It is not clear to me whether the (non-neglectible) work to develop something nice would be worth it for Merlin. Do you have many other instances of such fiddly things in the codebase? Otherwise just proper comments may be a better deal.
