### ISSUE TITLE
Fieldslib: Merlin requires opening Core.Std

### ISSUE THREAD

**Issue by xguerin** [the-lambda-church/merlin#359]
When creating a simple .ml with the following:

    type t = {
        a: int;
        b: int;
     } with fields

Merlin complains about the following: `Unbound module Field`. Adding `open Core.Std` fixes the complains, but forces me to include `Core.Std` even though I don't need it (and it conflicts with `Bistring`). My `.merlin` file contains `PKG core`. Am I forgetting something ?

**Comment by trefis** [comment]
Hi!
You're not forgetting anything, there was a problem in our binding requiring you to open Core.Std (or Fieldslib). This is fixed by 26f358d , which was committed just after the last release (v2.1.1).

If this is too annoying to wait for the next release (which we honestly have no ETA for) you can always use the git version of merlin (opam pin is your friend!).
