### ISSUE TITLE
Is there a way to tell merlin "don't try to do anything about a buffer that is unsaved"?

### ISSUE THREAD

**Issue by UnixJunkie** [the-lambda-church/merlin#374]
Like, don't try to parse it until its saved.

**Comment by trefis** [comment]
`M-x merlin-mode`.

**Comment by dbuenzli** [comment]
@trefis It seems to me that this will disable merlin mode but will not automatically reenable it on the next save.

**Comment by trefis** [comment]
That is true.
I guess you can also `(add-hook 'after-save-hook 'merlin-mode ....)` or something similar.

**Comment by dbuenzli** [comment]
There are cases where merlin gives me wrong signals and the error overlay is annoying. E.g. because I'm refactoring things or because it mysteriously doesn't find things (sometimes it's just that you forgot a `PKG` instruction, but sometimes not) and you don't want to bother immediately.

At a certain point I suggested to @def-lkb to remove the overlay a fews secs after you started typing again, but in the end I'm not sure that this is good idea, sometimes you still want to see the error overlay while you type. I think that an easy accessible shortcut to toggle the overlay until the next save would be nice. I'd suggest `C-c C-SPC`, this would toggle the visible overlay and if rendered invisible only at most until the next save.

**Comment by dbuenzli** [comment]
Related to #273

**Comment by trefis** [comment]
Well, there is already something to disable error checking I believe (see `merlin-error-after-save`), but it is not as convenient as what you're asking for indeed.
I will try to implement that next week; of course my elisp skills are not great, so it might be better done by an emacs user like you, @gasche or @gsg.

**Comment by UnixJunkie** [comment]
My initial question came because I understood (because my emacs was lagging) that merlin
sometime does heavy things in the background.
I think that some users would prefer that merlin does its job only at startup and upon any
file of the project being saved (after a modification) rather than always working in the background.
And, I already turned off everything I could in merlin.

**Comment by trefis** [comment]
> My initial question came because I understood (because my emacs was lagging) that merlin
sometime does heavy things in the background.

Do you have any proof of that? Like "top told me that merlin was monopolizing my CPU" or something?
I ask because merlin doesn't actually do anything unless you call it explicitly.

**Comment by UnixJunkie** [comment]
Yes, my emacs lagging is a proof.
Without merlin, I never observe it lagging.
Maybe the emacs merlin mode is the culprit, maybe not merlin itself.

**Comment by trefis** [comment]
Well then my initial answer is perfect for you I guess.
Of course with a bit more information (what system you're on, what version of emacs you're running) we could actually try to look for what's causing these lags than no one complained about before. But that would probably be overdoing it.

**Comment by UnixJunkie** [comment]
I C-g my lagging emacs; in the *Messages* buffer:
Error during redisplay: (eval (merlin-lighter)) signaled (quit)

**Comment by gsg** [comment]
Does the lag go away if you eval `(defun merlin-lighter () "merlin")` (after starting up)?

**Comment by UnixJunkie** [comment]
I'll try.

**Comment by trefis** [comment]
Hi!

Sorry for the late answer...
The error you found in `*Messages*` is really helpful, it points us to a part of the emacs mode I forgot existed, and which does indeed run some idle jobs... Sorry for that.

Several people have been having problems with it, and we discovered it was buggy. This has been fixed by https://github.com/the-lambda-church/merlin/commit/a5a4ab913dc264ba745f71b9637df655fe4db155

If this is the problem which was affecting you, then @gsg's snippet should have made the problem disappear. Is that the case, or do we need to keep looking?

**Comment by UnixJunkie** [comment]
Can I put the snippet from @gsg in my .emacs?

**Comment by UnixJunkie** [comment]
apparently yes so I am trying this workaround now

**Comment by trefis** [comment]
Any news?

**Comment by UnixJunkie** [comment]
I think it is OK, since I didn't notice any lag for some time.

**Comment by trefis** [comment]
Great, thank you!
