### ISSUE TITLE
better error reporting when flags do not match

### ISSUE THREAD

**Issue by gasche** [the-lambda-church/merlin#410]
I am trying to sell Merlin to Coq users that write plugins in OCaml. When writing plugins outside the Coq directory, they need to have a `.merlin` of the following form:

```
FLG -rectypes
S path-to-coq/**
B path-to-co/**
```

Unfortunately, if they forget the `FLG -rectypes` part, the `.cmi` modules do not get loaded and, from an end-user point of view, *nothing works*: type lookup systematically fails with "no result". I was unable to get an explanation of what goes wrong from Merlin itself, and this is the issue I am reporting.

It would be much better to have a nice error message, either at `.merlin`-loading files (I am giving a `B` path to a place full of `cmi` that all have `-rectypes`, and thus cannot be loaded without the flag), or at `C-c C-t` time (I am looking for a module that has no valid `.cmi` file, but has a `.cmi` file in the build path that would work with `-rectypes` enabled).

**Comment by gasche** [comment]
I uploaded a minimal repro-case for this issue as [merlin-issue-410.zip](http://gallium.inria.fr/~scherer/tmp/merlin-issue-410.zip). Running `sh comp.sh`, then `emacs user.ml` will open a file that accesses two libraries, `Lib` and `Lib2`, where the former requires `-rectypes` during compilation, and the flag has *not* been set in `.merlin`. In my machine there is no error/warning whatsoever, but from `user.ml` querying the signature of `Lib2` works, while it fails with "no result" for `Lib`.

**Comment by trefis** [comment]
So... It won't show up when you load the .merlin (because we don't load all the cmis available in your build path when we load the .merlin, when we need a cmi we look for it in the supplied build path) nor when you ask for a type because we never report any errors when you run that command, or when you complete, or whenever. We will report the error when you explicitly ask for error, as usual.

There was a bug preventing this kind of error from showing up when you manually ask for errors, this is now fixed.
