### ISSUE TITLE
Question about comments/docstrings

### ISSUE THREAD

**Issue by fxfactorial** [the-lambda-church/merlin#437]
Does merlin preserve docstrings ? aka the (** some documentation *) during lexing/parsing?

**Comment by def-lkb** [comment]
This is only partially implemented. Do you have specific needs?

**Comment by fxfactorial** [comment]
I have this in Python, I want this with merlin 

![screen shot 2015-09-29 at 10 44 47 am](https://cloud.githubusercontent.com/assets/3036816/10173063/417455e2-6697-11e5-8c69-9adb7cd26551.png)

**Comment by def-lkb** [comment]
Fixed in upcoming release.

- enable documentation support `(setq merlin-completion-with-doc t)`
- with *auto-complete*, latest version will report documentation using `:document`, no customization needed
- with *company*, documentation is integrated into `doc-buffer`, press `F1` or `C-h` to get doc while completing. Alternatively, you can install [company-quickhelp](https://github.com/expez/company-quickhelp), after `(company-quickhelp-mode 1)` documentation will 
e displayer in a tooltip like in the screenshot

**Comment by fxfactorial** [comment]
Awesome! Thanks!
