### ISSUE TITLE
Ordering 'destruct' display

### ISSUE THREAD

**Issue by Fourchaux** [the-lambda-church/merlin#441]
With Merlin_master, Emacs mode, OCaml 4.02.3

e.g. with :
```ocaml
type union =
  | Cas1 of int
  | Cas2 of int * string * bool
  | Cas3

let f x = match x with
  | Cas3 -> ()
```
Currently, a 'destruct' on Cas3 gives :
```ocaml
let f x = match x with
  | Cas3 -> ()
  | Cas1 _
  | Cas2 (_,_,_) -> failwith "TODO"
```
Would be better (I think) to have :
```ocaml
let f x = match x with
  | Cas1 _       -> failwith "TODO"
  | Cas2 (_,_,_) -> failwith "TODO"
  | Cas3         -> ()

Or 

let f x = match x with
  | Cas1 _
  | Cas2 (_,_,_)
  | Cas3         -> ()
```
That is, with the same order as in the type declaration.

And ditto for :
```ocaml
let f = function
| Cas3 -> ()
```
etc...

**Comment by trefis** [comment]
Feel free to submit a PR for that, but I feel like this is not important enough and way to annoying to implement to actually spend time on it.
Notice that if you implement this, the following behavior should be respected:

```ocaml
type alphab = A | B | C | E | D | F

let f = function
  | B -> ()
  | E -> ()
```
should become:
```ocaml
type alphab = A | B | C | E | D | F

let f = function
  | A -> failwith "TODO"
  | B -> ()
  | C -> failwith "TODO"
  | E -> ()
  | D
  | F -> failwith "TODO"
```

Keep in mind that you don't want to reprint in any way the code already written by the user (because you might desugar, change indentation, etc) and that if you modify the protocol too much to accommodate things like this you will have a wonderful time playing with emacs and vimscript.
