### ISSUE TITLE
Locate goes to signature/alias instead of implemenation

### ISSUE THREAD

**Issue by vogler** [the-lambda-church/merlin#521]
Having `merlin_locate_preference = 'ml'` I would expect `MerlinLocate` to always jump to the implementation.

Example `locate_sig.ml`:
~~~ocaml
module type S = sig
  val x : int
end
module A : S = struct
  let x = 1
end
module F (A: S) : S = struct
  let x = A.x
end
module B = F (A)
let _ = A.x + B.x (* test here *)
~~~
Locate on `A.x`/`B.x` jumps to `val x` instead of the corresponding `let x`.
When `S` is removed on `A`/`B`, it jumps to the implementation as expected.

Trying the same from another file `locate_open.ml`, however, leads to really unexpected behavior:
~~~ocaml
open Locate_sig
let _ = A.x + B.x
~~~
Now, locate on `A.x` jumps to `let x` in `A`, while locate `B.x` jumps to the alias `module B`.

**Comment by trefis** [comment]
When you locate something, merlin first looks into its environment (i.e. the environment built by the typechecker), if there is a source location in there, it uses that. Otherwise it will start inspecting the typedtree of your file(s).

The option is used only to guide what happens in the second case, in the first case (which is what happens in your example) it is not used.

**Comment by vogler** [comment]
Are you saying that it uses the environment in both examples? Why does it yield different locations then?

**Comment by trefis** [comment]
In the second example, `A.x` and `B.x` come from another file, so you don't have location information in the environment.

**Comment by vogler** [comment]
I see, thanks!

How sensible/feasible are:
1. always using typedtree instead of the environment
2. resolving module aliases (`B.x` in ex 2)
