### ISSUE TITLE
Conflict with neovim?

### ISSUE THREAD

**Issue by liweijian** [the-lambda-church/merlin#536]
There's an error when I using Neovim to edit OCaml's file:
![7 pic](https://cloud.githubusercontent.com/assets/19320783/15504693/bf9568d2-21f2-11e6-9f50-14002354742c.jpg)

I tried to debug the `init.vim` file, when I comment this, there's no error anymore:
> execute "set rtp+=" . g:opamshare . "/merlin/vim"

The `g:opamshare` in my neovim was:
> ~/.opam/4.02.3/share/merlin/vim/

And that's no an empty folder:
```bash
$ ls ~/.opam/4.02.3/share/merlin/vim/
autoload        ftdetect        plugin          syntax_checkers
doc             ftplugin        syntax
```

**Comment by let-def** [comment]
You are mixing incompatible merlin binary and mode.

**Comment by liweijian** [comment]
Thanks, it works now:)

**Comment by liweijian** [comment]
@let-def  Right now I could use Merlin from neovim in terminal, there's an config in my fish shell
```bash
$ grep "opam" ~/.config/fish/config.fish
eval (opam config env)
```

However, when I use the [gnvim](https://github.com/rogual/neovim-dot-app/blob/master/gnvim) mode, merlin doesn't works, it seems that the Neovim's GUI version could detect the environment.

**Comment by let-def** [comment]
This is a peculiarity of Mac OS X shell launcher.

I don't know how exactly to "solve" it.
Sometime, the shell profile is sourced when opening the session, so logging in/out can help provided you don't switch opam too often.
Otherwise, you will have to simulate sourcing your profile from gnvim. I don't know how to achieve that, but there should already be some resources available online.
