### ISSUE TITLE
Showing documentation comments

### ISSUE THREAD

**Issue by roshanjames** [the-lambda-church/merlin#55]
Can you scrape off the documentation comments that precede most function definitions in mli files and show these in some way -- maybe as a help tooltip.

**Comment by trefis** [comment]
So, I have a branch ( `ocamldoc` ) which does that.
Remarks:
- it retrieves documentation comments from the cmts, not from sources. This means that if your build system uses camlp4, you won't have any documentation from merlin (as camlp4 drops the comments, so there's nothing in the cmts)
- the integration with vim/emacs is rudimentary, I am still working on it
- I'm reluctant to bind this to K in vim, K does work with ocaml (at least with the stdlib) and I'm not sure we want to break that.

**Comment by roshanjames** [comment]
Thomas, this is a great step forward.

**Comment by edwintorok** [comment]
I see that this is now in Merlin 2.2, great job!
In emacs it works when I use `company` mode for completion and press F1, but not with `auto-complete`.
Is company mode the [prefered completion engine for merlin](https://github.com/edwintorok/spacemacs/commit/e8bdaa69e671024531662522ca301d2c200a2944#commitcomment-11337704) or is it [auto-complete](https://github.com/syl20bnr/spacemacs/issues/1674#issuecomment-104659397)?

**Comment by def-lkb** [comment]
If there was a favorite completion engine, I would say `company-mode`, because it's the one I use the most when I maintain emacs mode.

I am working on [emacschism](https://github.com/the-lambda-church/merlin/tree/emacschism/emacs) branch, to separate core merlin management from integration with other emacs services, in the hope it will make it easier to maintain and attract externel contribution.

**Comment by let-def** [comment]
Implemented for some time. More communication around the feature is coming.
