### ISSUE TITLE
Relative paths for ppx

### ISSUE THREAD

**Issue by chenglou** [the-lambda-church/merlin#571]
@let-def as discussed in chat: it'd be nice to have a `PPX` section that accepts relative paths to ppx, just as `S` and `B` do. Or maybe make the `FLG` section relative.

**Comment by let-def** [comment]
Implemented in next version (relative paths for FLG).

**Comment by let-def** [comment]
# Expansion of flag arguments

When a flag receives a path argument, the argument is resolved relatively to the directory of thebuffer (for command-line arguments) and to the of the `.merlin` file (for `FLG` directive).

Expansion is done as follow:  
- _absolute_ paths, such as `/tmp/test`, are not touched,  
- _relative_ paths, such as `./test`, are always expanded,  
- _filenames_, such as `test`, are expanded except for binaries, which are searched for in the `$PATH` variable.

**Comment by vramana** [comment]
@let-def This doesn't seem to work. In my case,

```
# Works
FLG -ppx /home/vramana/Documents/reasonml/rebel/examples/bs-project/node_modules/bs-platform/bin/bsppx

# Doesn't work
FLG -ppx ./node_modules/bs-platform/bin/bsppx
 ```

**Comment by raphael-proust** [comment]
@vramana can you give the output for both case? (“Doesn't work” is not as helpful as the output.)

**Comment by vramana** [comment]
@raphael-proust Sorry. I am using atom-reason which uses merlin underneath. By not working I meant, it doesn't show any type inference or autocompletions.  When it works, it shows both type inferences and autocompletions.

**Comment by raphael-proust** [comment]
Haven't used atom for OCaml development. Maybe merlin output things to the console. Can you check the Developer Tools in Atom (“view” -> “Developer” -> “Toggle Developer Tools”)?

(It looks like `atom-ocaml-merlin` does that: https://github.com/314eter/atom-ocaml-merlin/search?utf8=✓&q=console. but I'm not sure what atom plugin you are using.)

**Comment by vramana** [comment]
[atom-reason](https://github.com/facebook/reason/tree/master/editorSupport/atom-reason) is an atom plugin for [reason](https://facebook.github.io/reason/).  

The issue is reproducible on [this repo](https://github.com/vramana/Rexpress/tree/merlin-debug).  To reproduce the issue

1. Clone the repo
2. Checkout the merlin-debug branch
3. Run `npm install` to install bucklescript package `bs-platform`
4. Open an editor and try to infer types in the `src/express.re`. According to my experience, you shouldn't see any inferred types. In the `.merlin`, the ppx is passed via a relative path [here](https://github.com/vramana/Rexpress/blob/merlin-debug/.merlin#L39) 
5. If you change the ppx path to absolute path, then restart the editor, the merlin seems to infer types. 

I have saved the merlin log for a different project with the same ppx using relative and absolute paths. Here is the [gist](https://gist.github.com/vramana/95ba58afd696a2814f9919b06ac517ec). From the gist it looks like a the problem is with merlin. I hope I have provided enough information. If you need more information, I am happy to provide more info.

**Comment by let-def** [comment]
Only the experimental branch implements support for relative paths, it is not yet merged to master (lot of intrusive changes on the way).

**Comment by vramana** [comment]
@let-def Oh okay. Thanks!

**Comment by trou** [comment]
Is this fixed in master ?

**Comment by IgnoredAmbience** [comment]
As far as I can tell, this issue still hasn't been fixed in master or the latest release. I've just run into this and have had to work around with an absolute path to my ppx in the project's build directory.
