### ISSUE TITLE
Error starting vim - no such package "js"

### ISSUE THREAD

**Issue by Charlesetc** [the-lambda-church/merlin#580]
Any idea why this is happening whenever I open an ocaml file?
```
(merlin) findlib: js: Fl_package_base.No_such_package("js", "")
Failed to load some packages "js"
Press ENTER or type command to continue
```
Vimrc:
```
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
```

Merlin still works fine - thanks for the great tool!

Merlin version 2.5.0
Ocaml version 4.02.3
Vim version 7.4

**Comment by Charlesetc** [comment]
Also:
```
> vim --version | grep python
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
```

**Comment by let-def** [comment]
You have `PKG js` in some .merlin file?

**Comment by Charlesetc** [comment]
I do indeed - thanks, sorry bout that

**Comment by cpdean** [comment]
Wait does that mean the fix is to delete .merlin files?

I'm trying to use merlin to help me read irmin.  I open up this file, for example: https://github.com/mirage/irmin/blob/master/bin/main.ml

and get this error:
```
"bin/main.ml" 18L, 848C
(merlin) findlib: comparelib: Fl_package_base.No_such_package("comparelib", "")
(merlin) findlib: dolog: Fl_package_base.No_such_package("dolog", "")
Failed to load some packages "dolog", "comparelib"
Press ENTER or type command to continue
```

This is because the project lists various packages in a .merlin file: https://github.com/mirage/irmin/blob/master/.merlin

I feel like something is wrong with my system or with my merlin install.  What do these errors mean and how do I resolve them?

**Comment by Charlesetc** [comment]
@cpdean I think this means you've got to run `opam install comparelib` and `opam install dolog`

**Comment by raphael-proust** [comment]
@cpdean the `.merlin` files lists a project's dependencies. It lets merlin figure out the type of all the things you import from libraries because it lets merlin know about the libraries.

If a project has dependencies that are not installed on your system, merlin will complain about it. Same if you try to compile the project.

Install the dependencies and the problem will be solved.

**Comment by cpdean** [comment]
Ah -- yeah installing those packages seems to have taken care of things.

So does this mean that the `.merlin` file is out of sync with the list of packages in the `opam` file?  irmin still compiled and ran all of its tests without error before my installing these missing packages referenced in the `.merlin`.

Would you ever want `.merlin` and `opam` to list different package dependencies?

**Comment by let-def** [comment]
It seems to be out of sync, yes.

> Would you ever want .merlin and opam to list different package dependencies?
Not in the general case I think. Opam files are a bit more expressive though, for instance they allow optional dependencies.

**Comment by dbuenzli** [comment]
@cpdean Note also that technically `PKG` `.merlin` directives do not denote OPAM packages, but `ocamlfind` ones (yes it is a bit embarrassing to have so many different notions of packages but it can be explained from a historical perpsective; we are trying to simplify these issues but it will take some time).

**Comment by cpdean** [comment]
I have so many questions but this ticket probably isn't the place for them...
