### ISSUE TITLE
Question: merlin crashes editor for very large ml files

### ISSUE THREAD

**Issue by bobzhang** [the-lambda-church/merlin#582]
is there any way to tell merlin to not work on some files (per file basis)

**Comment by freebroccolo** [comment]
@bobzhang out of curiosity, how large is the file that causes that? From the point of view of the editor mode, it should be straightforward to check the file size and simply not try to sync it with merlin (assuming it doesn't crash the editor too).

**Comment by freebroccolo** [comment]
Also, do you have an example of such a file?

**Comment by bobzhang** [comment]
https://github.com/bloomberg/bucklescript/blob/master/jscomp/bin/whole_compiler.ml

**Comment by bobzhang** [comment]
vscode can handle such file size easily, but the plugin vscode-ocaml can not handle it https://github.com/hackwaly/vscode-ocaml/issues/63

**Comment by freebroccolo** [comment]
@bobzhang I just ran a little test adapting some of my reason code and it seems the vscode and merlin combination can handle the file. It does take merlin a little while to load it compared to a usual file but it doesn't freeze the UI. I suspect the problem showing up in that plugin might actually be due to the syntax highlighting causing the editor to freeze. So it may be a problem with the language grammar causing pathological behavior or perhaps a problem with the tokenizer itself (upstream).

**Comment by let-def** [comment]
What is crashing? Do you really a get a segmentation fault from the editor?

**Comment by freebroccolo** [comment]
@let-def What was happening is the editor UI was freezing. It was not a problem with merlin though but with the editor highlighting grammar for the OCaml plugin. There was some followup [here](https://github.com/Microsoft/vscode-textmate/issues/27). I think it is safe to close this.

**Comment by let-def** [comment]
Thanks. I would not be surprised you also encounter this problem with merlin. Don't hesitate to comment/open a new issue if that was the case :-)
