### ISSUE TITLE
merlin-locate on case insensitive mac os 

### ISSUE THREAD

**Issue by icristescu** [the-lambda-church/merlin#586]
I have merlin 2.5.0 on mac os x yosemite 10.10.5. I have the standard installation of mac os, which is case insensitive. I am using merlin from emacs, which is case sensitive.

When I use C-c C-l to locate the definition of a function `Module.function` located in the file `module.ml`, merlin looks for the upper case file `Module.ml` and opens up file `module.ml` as `Module.ml`. If I modify and save the file, the name of `module.ml` changes to `Module.ml`, leading to problems for the compilation and git.

**Comment by raphael-proust** [comment]
Can you confirm the following just be sure :

Your OS is case-insensitive for opening files (i.e., when you try to open `module.ml`, passing `Module.ml` as arguments works).
But it is case sensitive for writing files (and more specifically, when writing to `Module.ml` it creates a new file `Module.ml` and deletes the old file `module.ml`).

Do you know if there is a way (other than listing all the files in the directory) to retrieve the *true name* of a file?

Also, I'm a bit curious to know what happens if you clone a repository that has two files with names that only differ by capitalisation… Do you know?

**Comment by let-def** [comment]
@raphael-proust: I am in the process of implementing that :). I have a way compatible with OS X, I am trying to find windows way

**Comment by dbuenzli** [comment]
Related to #425.

**Comment by dsheets** [comment]
The default HFS+ configuration is case-insensitive case-preserving (so insensitive for opening/reading but sensitive during creation).

As far as I know, the only way to get the true name of a file on OS X (besides `readdir`) is to use `getattrlist(2)` with the `ATTR_CMN_NAME` attribute. See [dsheets/ocaml-osx-attr](https://github.com/dsheets/ocaml-osx-attr).

**Comment by icristescu** [comment]
When I open manually the file `Module.ml` from emacs it opens `module.ml`. When merlin does it the file is renamed to `Module.ml`. 

Indeed for writing the file, the behaviour you mentioned, occurs: if `Module.ml` is saved, it replaces the file `module.ml`. 

I cannot have two files `Module.ml` and `module.ml` in the same repository.

**Comment by let-def** [comment]
@dbuenzli: here is my implementation of the feature:

```c
int fd = open(path, O_EVTONLY | O_NOFOLLOW);
if (fd != -1)
{
	char realpath_c[MAXPATHLEN];
	if (fcntl(fd, F_GETPATH, realpath_c) != -1)
	{
		puts(realpath_c);
	};
	close(fd);
}
```

**Comment by let-def** [comment]
ˆˆ oops, @dsheets, sorry dbuenzli :)

**Comment by let-def** [comment]
I pushed some code in master trying to deal with case insentivity.
Can you check if it improves your situation?

**Comment by let-def** [comment]
To directly try the git version: `opam pin merlin --dev-repo`

**Comment by icristescu** [comment]
It works, thank you very much.

**Comment by dsheets** [comment]
@let-def ah, that's neat! Thanks for the tip!
