### ISSUE TITLE
Merlin as a library 

### ISSUE THREAD

**Issue by fxfactorial** [the-lambda-church/merlin#588]
I have an idea that I wanted to use merlin as a library for but it doesn't seem to be the case that merlin exposes a META file. 

Could you please expose merlin as a library and show an easy to use example that shows how to use Merlin_{browse, lexer, lib, parser, typer, etc} together?

**Comment by let-def** [comment]
Merlin is not available as a library because:
* Merlin and more generally the OCaml frontend manipulate a lot of stateful components for which it is difficult to expose clean abstractions and that are difficult to use correctly,
* on top of that, Merlin adds hacks that stay "binary compatible" with upstream compiler but are slightly different internally, so it is very likely that mixing them in new ways would be unsafe.
* (bonus: this is a difficult feature and we just don't have the resources to implement it without more incentives)

May I ask what you want to do?

**Comment by fxfactorial** [comment]
@let-def I wanted to make an OCaml dedicated native IDE on OSX using merlin as a library and ocamldebug

**Comment by let-def** [comment]
This is overall a bad idea. I think you should use (and be happy to use) merlin as a process.

This provides lightweight coupling and easy asynchronous processing, imposes strong boundaries on failure and state corruption (just restart merlin), and eases interoperation with other ocaml tools: because merlin embeds it's own version of compiler libs, the risk of module conflict is high.

However, providing an API for remote control would be a saner option.

**Comment by fxfactorial** [comment]
Okay

**Comment by Leonidas-from-XIV** [comment]
What do you think about exposing some choice parts of Merlin? Specifically, I wanted to parse `.merlin` files and ended up writing a simple parser but the `Dot_merlin` module looks like it provides exactly this functionality.

**Comment by rgrinberg** [comment]
Maybe it just makes sense to add some functionality to query the .merlin file with the RPC protocol? E.g. dump it as json or sexp for example.
